name: Build
on:
  workflow_dispatch:
  workflow_call:

jobs:
  show-matrix:
    name: Show matrix

    strategy:
      matrix:
        include:
          - os: ubuntu-22.04-arm
            target: aarch64-unknown-linux-gnu
          - os: ubuntu-22.04-arm
            target: aarch64-unknown-linux-musl

          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl

          - os: macos-latest
            target: aarch64-apple-darwin

          - os: windows-latest
            target: aarch64-pc-windows-msvc
          - os: windows-latest
            target: x86_64-pc-windows-msvc

    runs-on: ${{ matrix.os }}
    steps:
      - name: Show matrix
        run: 'echo "Target: ${{ matrix.target }} Operating system: ${{ matrix.os }}"'

      - name: update linker
        if: ${{ matrix.os == 'ubuntu-22.04-arm' && matrix.target == 'aarch64-unknown-linux-musl' }}
        run: |
          sudo apt-get update
          sudo apt-get install musl-dev -y

      - name: Change to nightly toolchain
        run: rustup default nightly

      - name: Install target
        run: rustup target add ${{ matrix.target }}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Release build
        run: |
          mkdir -p target
          cargo build --release --target ${{ matrix.target }} --message-format=json > target/build_msg.json

      - name: Rename artifacts
        run: |
          mkdir -p target/artifacts
          executable_path=$(jq 'select(.reason == "compiler-artifact" and .target.kind[0] == "bin") | .executable' -r target/build_msg.json)
          file_name=$(basename "$executable_path")
          base_name="${file_name%.*}"
          extension="${file_name##*.}"
          if [[ "$file_name" == "$base_name" ]]; then
            new_file_name="${base_name}-${{ matrix.target }}"
          else
            new_file_name="${base_name}-${{ matrix.target }}.${extension}"
          fi
          mv "$executable_path" "target/artifacts/${new_file_name}"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}
          path: target/artifacts/${new_file_name}
          retention-days: 1
