name: Build
on:
  workflow_dispatch:
jobs:
  show-matrix:
    name: Show matrix

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
          - os: ubuntu-latest
            target: aarch64-unknown-linux-musl
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl

          - os: macos-latest
            target: aarch64-apple-darwin

          - os: windows-latest
            target: aarch64-pc-windows-msvc
          - os: windows-latest
            target: x86_64-pc-windows-msvc

    runs-on: ${{ matrix.os }}
    steps:
      - name: Show matrix
        run: 'echo "Target: ${{ matrix.target }} Operating system: ${{ matrix.os }}"'

      - name: update linker
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt-get update
          sudo apt-get install lld -y

      - name: Change to nightly toolchain
        run: rustup default nightly

      - name: Install target
        run: rustup target add ${{ matrix.target }}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Release build
        run: cargo build --release --target ${{ matrix.target }} -Z unstable-options --artifact-dir target/artifacts/${{ matrix.target }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4

        with:
          name: ${{ matrix.target }}
          path: target/artifacts/${{ matrix.target }}
          retention-days: 1
