name: Build
on:
  workflow_dispatch:
  workflow_call:

jobs:
  show-matrix:
    name: Show matrix

    strategy:
      matrix:
        include:
          - os: ubuntu-22.04-arm
            target: aarch64-unknown-linux-gnu
          - os: ubuntu-22.04-arm
            target: aarch64-unknown-linux-musl

          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl

          - os: macos-latest
            target: aarch64-apple-darwin

          - os: windows-latest
            target: aarch64-pc-windows-msvc
          - os: windows-latest
            target: x86_64-pc-windows-msvc

    runs-on: ${{ matrix.os }}
    steps:
      - name: Build Package
        run: 'echo "Target: ${{ matrix.target }} Operating system: ${{ matrix.os }}"'

      - name: update linker
        if: ${{ matrix.os == 'ubuntu-22.04-arm' && matrix.target == 'aarch64-unknown-linux-musl' }}
        run: |
          sudo apt-get update
          sudo apt-get install musl-dev -y

      - name: Change to nightly toolchain
        run: rustup default nightly

      - name: Install target
        run: rustup target add ${{ matrix.target }}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Release build
        run: |
          mkdir -p target
          cargo build --release --target ${{ matrix.target }} --message-format=json > target/build_msg.json

      - name: Rename artifacts
        shell: bash
        run: |
          mkdir -p target/artifacts/${{ matrix.target }}
          executable_path=$(jq 'select(.reason == "compiler-artifact" and .target.kind[0] == "bin") | .executable' -r target/build_msg.json)
          cp "$executable_path" "target/artifacts/${{ matrix.target }}/"
          executable_name=$(basename "$executable_path")
          artifact_path=target/artifacts/${executable_name%.*}_${{ matrix.target }}.tar.gz
          tar -zcf "$artifact_path" -C "target/artifacts/" "${{ matrix.target }}"

          echo "artifact_path=${artifact_path}" >> $GITHUB_ENV

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}
          path: ${{ env.artifact_path }}
          retention-days: 1
